### ISSUE TITLE
[RFE] Support Object Annotations

### ISSUE THREAD

**Issue by kreynoldsf5** [f5devcentral/f5-appsvcs-templates#5]
Currently, a template level annotation is available at the top of a FAST template:

```
{{!
  A simple HTTP application with HTTP load balancing. Provide a virtual address
  and port to host on, and a list of HTTP server IP addresses and a port to
  load balance requests to.
}}
```

Annotations at the object level should be supported. AS3 supports a ``remark`` property of format: f5remark (for all traffic objects, correct?). Perhaps this property could be used to provide the FAST annotation.

**Comment by zinkem5** [comment]
FAST templates support a YAML superset of JSON Schema for specifying templates and variable types beyond the simple description as above. 

The following simple template:

```
{{! this is a template }}
{
  declaration: {{a_variable}}
}
```

Is equivalent to this advanced template:

```yaml
description: this is a template
template: |
 {
  declaration: {{a_variable}}
 }
```

Another advanced template example:

```yaml
title: A useless template to specify a constrained JSON object
description: A template that constructs a JSON object with a single port property
definitions:
  validPort:
    title: Port
    description: A valid port in the range of 0 to 65535
    type: integer
    minimum: 0
    maximum: 65535
template: |
  {
    port: {{myPort::validPort}}
  }
```

Some of these titles and descriptions are used in the UI today if provided, and some will be added in the future. 

This leaves the AS3 fields open for AS3 specific annotations. Remarks, comments, labels and other AS3 metadata can be included as part of the template text, entered by the user (if parameterized by the template author), or constructed from template parameters.

We are working on delivering documentation,  but we have a (bare) advanced templating example using partials (they work like includes). It references the JSON-schema in the same directory, f5.json.

https://github.com/f5devcentral/f5-appsvcs-templates/blob/master/templates/bigip-fast-templates/http.yml


I will leave this ticket open until these advanced features are better documented.
